### ISSUE TITLE
Add local Web Server command to CLI application

### ISSUE THREAD

**Issue by vst** [teloscube/decaf-client-haskell#10]
- [x] Implement homepage that lists profiles (`/`) along with links to their detail pages.
- [x] Implement profile detail page (`/profiles/<profile-name>`):
  - [x] Show basic profile details (name, URL, credential type)
  - [x] Show link to Barista API Documentation (`/api`)
  - [x] Show link to Microlot GraphiQL
  - [x] Show link to Module PDMS GraphiQL
- [x] Implement Microlot GraphiQL page (`/profiles/<profile-name>/graphiql/microlot`)
- [x] Implement Module PDMS GraphiQL page (`/profiles/<profile-name>/graphiql/module-pdms`)

Keeping the original ticket description for reference:

> It would be nice if the user can launch [GraphiQL](https://github.com/graphql/graphiql) using the `decafcli` application, something like:
> 
> ```sh
> decafcli graphiql \
>   --file-profiles ~/.decaf/profiles.yaml \
>   --profile testinvest \
>   --api [microlot|module-pdms] \
>   [--port 3333]
> ```
> 
> We can:
> 
> 1. Implement a tiny Web server that serves GraphiQL using CDN assets (See [example](https://github.com/graphql/graphiql/tree/main/examples/graphiql-cdn)), or
> 3. Launch [graphqurl](https://github.com/hasura/graphqurl) as a separate process.
> 
> The advantage of the first method is that it does not have a dependency requirement for the end-user. The latter will require graphqurl to be installed OR will install it automatically for the enduser.

**Comment by fkoksal** [comment]
We can use blaze for generating the html:

https://hackage.haskell.org/package/blaze-html
