### ISSUE TITLE
Make New Release v0.0.0.4

### ISSUE THREAD

**Issue by vst** [teloscube/decaf-client-haskell#19]
Blocked by #20.

**Comment by vst** [comment]
@fkoksal #20 is ready to review. If it works for you, too, we can cut the new release.

**Comment by fkoksal** [comment]
v0.0.0.4 is released.

**Comment by vst** [comment]
@fkoksal 

**Quick note:** `decaf-client.cabal` is not updated although `package.yaml` is updated. To make sure that it is updated, you need to run `stack build` after updating `package.yaml`.

**Comment by fkoksal** [comment]
👍🏻
