### ISSUE TITLE
Adopt Nix Flake

### ISSUE THREAD

**Issue by vst** [teloscube/decaf-client-haskell#36]
I think that we should slimdown. Closing #35 in favour of this.

**Comment by fkoksal** [comment]
👍🏻

**Comment by vst** [comment]
After some thought: we should add Nix Flake support but we should not remove legacy support. 

See for an example setup: https://github.com/vst/haskell-hebele-hubele/blob/85491af0e3d25c6986529da5bdebf8890741958a/flake.nix#L1C1-L20

**Comment by vst** [comment]
Recently, let's postpone our Nix Flake endeavor. I do not think that it has significant marginal value at the moment.

Closing in favour of #37.
